# Generated by Django 5.0.4 on 2024-05-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_societyowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyowner',
            name='cnic',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
