# Generated by Django 5.0.4 on 2024-05-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_societyowner_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyowner',
            name='owner_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
