# Generated by Django 5.0.4 on 2024-04-30 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0003_societyowner'),
        ('Building', '0004_alter_announcement_announcement_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gatekeeper',
            fields=[
                ('id_number', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shift_time_day', models.CharField(max_length=10)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('current_status', models.CharField(max_length=100)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.society')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.user')),
            ],
        ),
    ]
