# Generated by Django 5.0.4 on 2024-04-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact_Information', models.TextField()),
                ('SSN_Number', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
