# Generated by Django 5.0.4 on 2024-04-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0003_societyowner'),
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contactInformation', models.TextField()),
                ('SSN_Number', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('currentStatus', models.CharField(max_length=100)),
                ('apartmentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.apartment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.society')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.user')),
            ],
        ),
    ]
