# Generated by Django 5.0.4 on 2024-04-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        ('Resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.user'),
        ),
    ]
