# Generated by Django 5.0.4 on 2024-04-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='resident_pictures/'),
        ),
    ]
