# Generated by Django 5.0.4 on 2024-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='SSN_Number',
            field=models.CharField(max_length=11),
        ),
    ]
