# Generated by Django 5.0.4 on 2024-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0002_alter_resident_ssn_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='id',
        ),
        migrations.AlterField(
            model_name='resident',
            name='SSN_Number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
