# Generated by Django 5.0.4 on 2024-04-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0002_resident_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='password',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
