# Generated by Django 5.0.4 on 2024-04-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resident', '0003_resident_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='password',
        ),
    ]
