# Generated by Django 5.0.4 on 2024-04-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenityId', models.AutoField(primary_key=True, serialize=False)),
                ('amenityName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('amenityStatus', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('openingHrs', models.CharField(max_length=100)),
                ('reservationFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance', models.TextField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dues_type', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('society_name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('total_apartments', models.PositiveIntegerField()),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=15)),
                ('number_of_floors', models.PositiveIntegerField()),
                ('number_of_blocks', models.PositiveIntegerField()),
                ('start_block', models.CharField(max_length=1)),
                ('end_block', models.CharField(max_length=1)),
                ('number_of_apartments_each_floor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('Apartment_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Floor_Number', models.IntegerField()),
                ('No_of_Rooms', models.IntegerField()),
                ('dues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.dues')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('reservationDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('amenity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Building.amenities')),
            ],
        ),
    ]
