# Generated by Django 5.0.4 on 2024-04-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dues_type', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apartment_number', models.IntegerField()),
                ('Floor_Number', models.IntegerField()),
                ('No_of_Rooms', models.IntegerField()),
                ('dues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.dues')),
            ],
        ),
    ]
