# Generated by Django 5.0.4 on 2024-04-20 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenityId', models.AutoField(primary_key=True, serialize=False)),
                ('amenityName', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('amenityStatus', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('openingHrs', models.CharField(max_length=100)),
                ('reservationFees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance', models.TextField()),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('reservationDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('residentSsn', models.CharField(max_length=11)),
                ('amenity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Building.amenities')),
            ],
        ),
    ]
