# Generated by Django 5.0.4 on 2024-04-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0001_initial'),
        ('Resident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resident.resident'),
        ),
        migrations.AddField(
            model_name='dues',
            name='society',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Building.society'),
        ),
    ]
