# Generated by Django 5.0.4 on 2024-04-29 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0003_societyowner'),
        ('Building', '0001_initial'),
        ('Resident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resident.resident'),
        ),
        migrations.AddField(
            model_name='society',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.user'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.society'),
        ),
    ]
