# Generated by Django 5.0.4 on 2024-04-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0002_amenities_reservations'),
        ('Resident', '0003_remove_resident_id_alter_resident_ssn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='residentSsn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resident.resident'),
        ),
    ]
