# Generated by Django 5.0.4 on 2024-04-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.society')),
            ],
        ),
    ]
