# Generated by Django 5.0.4 on 2024-04-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0004_alter_announcement_announcement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='amenities',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Building.society'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amenities',
            name='amenityId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
