# Generated by Django 5.0.4 on 2024-05-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0005_remove_amenities_maintenance_amenities_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='number_of_apartments_each_floor',
        ),
    ]
