# Generated by Django 5.0.4 on 2024-05-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0006_remove_society_number_of_apartments_each_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Building.society'),
            preserve_default=False,
        ),
    ]
