# Generated by Django 5.0.4 on 2024-05-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0007_dues_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='dues',
            name='amount',
            field=models.FloatField(default=123.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dues',
            name='due_date',
            field=models.DateField(default='2024-5-5'),
            preserve_default=False,
        ),
    ]
