# Generated by Django 5.0.4 on 2024-05-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Building', '0005_remove_amenities_maintenance_amenities_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.society')),
            ],
        ),
    ]
