# Generated by Django 5.0.4 on 2024-05-04 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0008_dues_amount_dues_due_date'),
        ('GateManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('date_of_visit', models.DateField(default=django.utils.timezone.now)),
                ('entrance_time', models.TimeField(default=django.utils.timezone.now)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('apartment_number_to_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.apartment')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Building.society')),
            ],
        ),
    ]
