# Generated by Django 5.0.4 on 2024-05-04 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateManagement', '0002_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='date_of_exit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
